"""Versioned constants for CONFENGE_COMPOUNDING_STANDARD/1.0."""

from __future__ import annotations

SCHEMA = "CONFENGE_COMPOUNDING_STANDARD/1.0"
SCHEMA_VERSION = "1.0"
DEFINITION_ID = SCHEMA
TIMEZONE = "America/Sao_Paulo"
COHORT_DAYS = 28
COHORT_ORIGIN = "2026-01-05"
FRESHNESS_LAG_DAYS = 2
MATURE_ASSET_DAYS = 28
SINGLE_ASSET_LIFT_MAX = 0.60
MIN_COMPOUNDING_COHORTS = 3
MIN_EXPONENTIAL_COHORTS = 6
AICC_DELTA_MIN = 2.0
ROLLING_ORIGIN_RMSE_IMPROVEMENT_MIN = 0.05
ROLLING_ORIGIN_MIN_TRAIN = 3
STALE_RATE_MAX = 0.20
DEFECT_RATE_MAX = 0.10
PAYLOAD_STALE_DAYS = 14

PRIMARY_SERIES_NAME = "non_branded_clicks_approved_routes"
PRIMARY_SOURCE_FAMILY = "organic_non_branded"
NORTH_STAR_NAME = "inbound_qualified_pipeline_per_month_observed"

UNKNOWN = "UNKNOWN"
BLOCKED = "BLOCKED"
ZERO = "ZERO"
OBSERVED = "OBSERVED"

MISSING_SENTINELS = frozenset({UNKNOWN, BLOCKED, None})

SOURCE_FAMILIES = (
    "organic_non_branded",
    "organic_branded",
    "paid",
    "legacy_brand",
    "outbound",
    "partner",
    "direct",
)

CONTAMINATING_FAMILIES = frozenset(
    {"paid", "organic_branded", "legacy_brand", "outbound", "partner", "direct"}
)

CLASSIFIER_STATES = (
    "INSUFFICIENT_EVIDENCE",
    "PLATEAU_OR_DECAY",
    "LINEAR_CANDIDATE",
    "COMPOUNDING_CANDIDATE",
    "EXPONENTIAL_CANDIDATE",
)

HUMAN_ONLY_STATES = frozenset({"SCALE_ALLOWED"})
ALL_STATES = CLASSIFIER_STATES + ("SCALE_ALLOWED",)

COMPONENT_KEYS = (
    "input",
    "discovery",
    "qualified_use",
    "commercial",
    "moat",
    "efficiency",
)

ADVERSARIAL_KEYS = (
    "tracking_breaks",
    "seasonality",
    "serp",
    "migration",
    "launches",
)

FORBIDDEN_PII_KEYS = frozenset(
    {
        "query",
        "query_string",
        "gsc_query",
        "search_query",
        "email",
        "lead_email",
        "person_name",
        "cpf",
        "phone",
        "telefone",
        "whatsapp",
        "lead_id",
        "person_id",
        "user_email",
    }
)

FORBIDDEN_JOIN_FLAGS = frozenset(
    {
        "query_to_lead_join",
        "gsc_query_to_lead",
        "query_to_person",
    }
)

INFERRED_MARKERS = frozenset(
    {
        "inferred",
        "inferred_from_clicks",
        "pipeline_estimated_from_clicks",
        "outcome_inferred",
    }
)

REASON_INCOMPLETE_WINDOW = "INCOMPLETE_WINDOW"
REASON_DEFINITION_CHANGED = "DEFINITION_CHANGED"
REASON_INCOMPATIBLE_SOURCE = "INCOMPATIBLE_SOURCE"
REASON_MISSING_DENOMINATOR = "MISSING_DENOMINATOR"
REASON_INVALID_CLOCK = "INVALID_CLOCK"
REASON_LATE_ARRIVAL_UNRECONCILED = "LATE_ARRIVAL_UNRECONCILED"
REASON_AGGREGATE_WITHOUT_PROVENANCE = "AGGREGATE_WITHOUT_PROVENANCE"
REASON_QUERY_LEVEL_PII = "QUERY_LEVEL_PII"
REASON_INFERRED_OUTCOME = "INFERRED_OUTCOME"
REASON_MIXED_SOURCE_FAMILIES = "MIXED_SOURCE_FAMILIES"
REASON_INSUFFICIENT_COHORTS = "INSUFFICIENT_COHORTS"
REASON_TRACKING_BREAK = "TRACKING_BREAK"
REASON_SINGLE_ASSET_DOMINANCE = "SINGLE_ASSET_DOMINANCE"
REASON_COMMERCIAL_GUARDRAIL_DETERIORATED = "COMMERCIAL_GUARDRAIL_DETERIORATED"
REASON_COST_EXCEEDS_DEMAND = "COST_EXCEEDS_DEMAND"
REASON_STALE_PAYLOAD = "STALE_PAYLOAD"
REASON_DEFECT_SPIKE = "DEFECT_SPIKE"
REASON_PAID_CONTAMINATION = "PAID_CONTAMINATION"
REASON_BRANDED_CONTAMINATION = "BRANDED_CONTAMINATION"
REASON_LEGACY_SMARTLIC_CONTAMINATION = "LEGACY_SMARTLIC_CONTAMINATION"
REASON_DIRECT_CONTAMINATION = "DIRECT_CONTAMINATION"
REASON_OVERLAPPING_WINDOWS = "OVERLAPPING_WINDOWS"
REASON_RETROACTIVE_REDEFINITION = "RETROACTIVE_REDEFINITION"
REASON_SCALE_NOT_AUTO = "SCALE_NOT_AUTO"
REASON_LINEAR_BETTER_THAN_LOG = "LINEAR_BETTER_THAN_LOG"
REASON_LEAVE_ONE_OUT_FAILED = "LEAVE_ONE_OUT_FAILED"
REASON_LEAVE_ONE_OUT_INFEASIBLE = "LEAVE_ONE_OUT_INFEASIBLE"
REASON_PAGE_COUNT_NOT_KPI = "PAGE_COUNT_NOT_KPI"
REASON_QUERY_TO_LEAD_JOIN_REFUSED = "QUERY_TO_LEAD_JOIN_REFUSED"
REASON_SYNTHETIC_ZERO_FORBIDDEN = "SYNTHETIC_ZERO_FORBIDDEN"
REASON_DEMAND_PER_ASSET_NOT_IMPROVING = "DEMAND_PER_ASSET_NOT_IMPROVING"
REASON_CLICKS_PER_ASSET_FALLING = "CLICKS_PER_ASSET_FALLING"
REASON_DEMAND_NOT_FASTER_THAN_ASSETS = "DEMAND_NOT_FASTER_THAN_ASSETS"
REASON_LOG_RATE_NOT_POSITIVE = "LOG_RATE_NOT_POSITIVE"
REASON_ADVERSARIAL_REVIEW_MISSING = "ADVERSARIAL_REVIEW_MISSING"
REASON_NORTH_STAR_UNKNOWN = "NORTH_STAR_UNKNOWN"
REASON_STALE_RATE_EXCEEDED = "STALE_RATE_EXCEEDED"
REASON_GSC_SYNC_BLOCKED = "GSC_SYNC_BLOCKED"
REASON_FORCE_CLOSE_INCOMPLETE = "FORCE_CLOSE_INCOMPLETE"
REASON_WALL_CLOCK_FORBIDDEN = "WALL_CLOCK_FORBIDDEN"
REASON_PRIMARY_SERIES_NOT_NON_BRANDED = "PRIMARY_SERIES_NOT_NON_BRANDED"

REASON_CODES = (
    REASON_INCOMPLETE_WINDOW,
    REASON_DEFINITION_CHANGED,
    REASON_INCOMPATIBLE_SOURCE,
    REASON_MISSING_DENOMINATOR,
    REASON_INVALID_CLOCK,
    REASON_LATE_ARRIVAL_UNRECONCILED,
    REASON_AGGREGATE_WITHOUT_PROVENANCE,
    REASON_QUERY_LEVEL_PII,
    REASON_INFERRED_OUTCOME,
    REASON_MIXED_SOURCE_FAMILIES,
    REASON_INSUFFICIENT_COHORTS,
    REASON_TRACKING_BREAK,
    REASON_SINGLE_ASSET_DOMINANCE,
    REASON_COMMERCIAL_GUARDRAIL_DETERIORATED,
    REASON_COST_EXCEEDS_DEMAND,
    REASON_STALE_PAYLOAD,
    REASON_DEFECT_SPIKE,
    REASON_PAID_CONTAMINATION,
    REASON_BRANDED_CONTAMINATION,
    REASON_LEGACY_SMARTLIC_CONTAMINATION,
    REASON_DIRECT_CONTAMINATION,
    REASON_OVERLAPPING_WINDOWS,
    REASON_RETROACTIVE_REDEFINITION,
    REASON_SCALE_NOT_AUTO,
    REASON_LINEAR_BETTER_THAN_LOG,
    REASON_LEAVE_ONE_OUT_FAILED,
    REASON_LEAVE_ONE_OUT_INFEASIBLE,
    REASON_PAGE_COUNT_NOT_KPI,
    REASON_QUERY_TO_LEAD_JOIN_REFUSED,
    REASON_SYNTHETIC_ZERO_FORBIDDEN,
    REASON_DEMAND_PER_ASSET_NOT_IMPROVING,
    REASON_CLICKS_PER_ASSET_FALLING,
    REASON_DEMAND_NOT_FASTER_THAN_ASSETS,
    REASON_LOG_RATE_NOT_POSITIVE,
    REASON_ADVERSARIAL_REVIEW_MISSING,
    REASON_NORTH_STAR_UNKNOWN,
    REASON_STALE_RATE_EXCEEDED,
    REASON_GSC_SYNC_BLOCKED,
    REASON_FORCE_CLOSE_INCOMPLETE,
    REASON_WALL_CLOCK_FORBIDDEN,
    REASON_PRIMARY_SERIES_NOT_NON_BRANDED,
)

METRIC_FIELDS = (
    "impressions",
    "clicks",
    "query_coverage_count",
    "engagement_admitted",
    "method_evidence_opened",
    "utility_completed",
    "content_to_service",
    "lead_valid",
    "lead_qualified",
    "meeting",
    "proposal",
    "qualified_pipeline_brl",
    "won",
    "lost",
    "contracted_revenue_brl",
    "received_revenue_brl",
    "citations",
    "referring_domains",
    "download_embed_reuse",
    "return_visits",
    "editorial_hours",
    "refresh_cost",
    "substantive_changes",
    "defects",
    "corrections",
    "stale_count",
    "attribution_coverage",
)
