"""Regression coverage for the generated crawler-control blocks."""

from __future__ import annotations

import os
import shutil
import subprocess
import sys
from pathlib import Path

import pytest

from scripts.contract_analysis.render import sync_family_crawler_rules


FIXTURES = Path(__file__).with_name("fixtures") / "crawler-controls-current"
ROOT = Path(__file__).resolve().parents[3]
CONTRACT_BEGIN = "# Contract-analysis family — generated by scripts.contract_analysis"
CONTRACT_END = "# Contract-analysis family — end"


@pytest.mark.parametrize(
    ("filename", "contract_rule", "following_marker"),
    [
        (
            "robots.txt",
            "Disallow: /analises-contratos-publicos/",
            "# Market-panorama family — generated by scripts.market_panorama",
        ),
        (
            "_headers",
            "/analises-contratos-publicos/*",
            "# Offer catalog preview: public gate still off",
        ),
    ],
)
def test_current_legacy_block_migrates_without_corrupting_following_family(
    tmp_path: Path,
    filename: str,
    contract_rule: str,
    following_marker: str,
) -> None:
    shutil.copyfile(FIXTURES / filename, tmp_path / filename)

    sync_family_crawler_rules([], root=tmp_path)

    rendered = (tmp_path / filename).read_text(encoding="utf-8")
    assert following_marker in rendered
    assert rendered.count(contract_rule) == 1
    assert rendered.count(CONTRACT_BEGIN) == 1
    assert rendered.count(CONTRACT_END) == 1


@pytest.mark.parametrize(
    ("filename", "following_block", "following_marker"),
    [
        (
            "robots.txt",
            "# Neighbor crawler policy\nDisallow: /vizinha/\n",
            "# Neighbor crawler policy",
        ),
        (
            "_headers",
            "# Neighbor crawler policy\n/vizinha/*\n  X-Robots-Tag: noindex\n",
            "# Neighbor crawler policy",
        ),
    ],
)
def test_legacy_empty_block_does_not_consume_an_adjacent_comment(
    tmp_path: Path,
    filename: str,
    following_block: str,
    following_marker: str,
) -> None:
    (tmp_path / filename).write_text(
        f"{CONTRACT_BEGIN}\n{following_block}", encoding="utf-8"
    )

    sync_family_crawler_rules([], root=tmp_path)

    rendered = (tmp_path / filename).read_text(encoding="utf-8")
    assert following_marker in rendered


@pytest.mark.parametrize(
    ("filename", "family_rule", "following_block"),
    [
        (
            "robots.txt",
            "Disallow: /analises-contratos-publicos/",
            (
                "# Neighbor crawler policy\n"
                "Disallow: /analises-contratos-publicos/\n"
                "Disallow: /vizinha/\n"
            ),
        ),
        (
            "_headers",
            "/analises-contratos-publicos/*",
            (
                "# Neighbor crawler policy\n"
                "/analises-contratos-publicos/*\n"
                "  X-Robots-Tag: noindex, nofollow, noarchive\n\n"
                "/vizinha/*\n"
                "  X-Robots-Tag: noindex\n"
            ),
        ),
    ],
)
def test_legacy_migration_removes_stale_duplicate_without_losing_marker(
    tmp_path: Path,
    filename: str,
    family_rule: str,
    following_block: str,
) -> None:
    (tmp_path / filename).write_text(
        f"{CONTRACT_BEGIN}\n{family_rule}\n{following_block}", encoding="utf-8"
    )

    sync_family_crawler_rules([], root=tmp_path)

    rendered = (tmp_path / filename).read_text(encoding="utf-8")
    assert "# Neighbor crawler policy" in rendered
    assert rendered.count(family_rule) == 1


@pytest.mark.parametrize(
    ("filename", "family_rule", "rule_body"),
    [
        (
            "robots.txt",
            "Disallow: /analises-contratos-publicos/",
            "Disallow: /analises-contratos-publicos/\n",
        ),
        (
            "_headers",
            "/analises-contratos-publicos/*",
            (
                "/analises-contratos-publicos/*\n"
                "  X-Robots-Tag: noindex, nofollow, noarchive\n\n"
            ),
        ),
    ],
)
def test_legacy_block_does_not_pair_with_a_later_duplicate_end_marker(
    tmp_path: Path,
    filename: str,
    family_rule: str,
    rule_body: str,
) -> None:
    (tmp_path / filename).write_text(
        (
            f"{CONTRACT_BEGIN}\n{rule_body}"
            "# Neighbor crawler policy\n"
            f"{CONTRACT_BEGIN}\n{rule_body}{CONTRACT_END}\n"
        ),
        encoding="utf-8",
    )

    sync_family_crawler_rules([], root=tmp_path)

    rendered = (tmp_path / filename).read_text(encoding="utf-8")
    assert "# Neighbor crawler policy" in rendered
    assert rendered.count(family_rule) == 1
    assert rendered.count(CONTRACT_BEGIN) == 1
    assert rendered.count(CONTRACT_END) == 1


def _robots_directives(payload: bytes) -> list[bytes]:
    return [
        line
        for line in payload.splitlines(keepends=True)
        if line.startswith((b"Allow:", b"Disallow:"))
    ]


def test_cli_build_twice_is_idempotent_and_preserves_crawler_policy() -> None:
    isolated_root = Path(os.environ["CONFENGE_CONTRACT_ANALYSIS_ROOT"])
    for filename in ("robots.txt", "_headers"):
        shutil.copyfile(FIXTURES / filename, isolated_root / filename)
    original_robots_policy = _robots_directives(
        (isolated_root / "robots.txt").read_bytes()
    )

    first = subprocess.run(
        [sys.executable, "-m", "scripts.contract_analysis", "build"],
        cwd=ROOT,
        capture_output=True,
        text=True,
        check=False,
    )
    assert first.returncode == 0, first.stderr + first.stdout
    once = {
        filename: (isolated_root / filename).read_bytes()
        for filename in ("robots.txt", "_headers")
    }
    assert _robots_directives(once["robots.txt"]) == original_robots_policy

    second = subprocess.run(
        [sys.executable, "-m", "scripts.contract_analysis", "build"],
        cwd=ROOT,
        capture_output=True,
        text=True,
        check=False,
    )
    assert second.returncode == 0, second.stderr + second.stdout
    twice = {
        filename: (isolated_root / filename).read_bytes()
        for filename in ("robots.txt", "_headers")
    }
    assert twice == once
