"""Regression coverage for the generated crawler-control blocks."""

from __future__ import annotations

import os
import shutil
import subprocess
import sys
from pathlib import Path
from types import SimpleNamespace

import pytest

from scripts.contract_analysis.render import sync_family_crawler_rules


FIXTURES = Path(__file__).with_name("fixtures") / "crawler-controls-current"
ROOT = Path(__file__).resolve().parents[3]
CONTRACT_BEGIN = "# Contract-analysis family — generated by scripts.contract_analysis"
CONTRACT_END = "# Contract-analysis family — end"
MARKET_BEGIN = "# Market-panorama family — generated by scripts.market_panorama"
MARKET_END = "# Market-panorama family — end"


@pytest.mark.parametrize(
    ("filename", "contract_rule", "following_marker"),
    [
        (
            "robots.txt",
            "Disallow: /analises-contratos-publicos/",
            "# Market-panorama family — generated by scripts.market_panorama",
        ),
        (
            "_headers",
            "/analises-contratos-publicos/*",
            "# Offer catalog preview: public gate still off",
        ),
    ],
)
def test_current_legacy_block_migrates_without_corrupting_following_family(
    tmp_path: Path,
    filename: str,
    contract_rule: str,
    following_marker: str,
) -> None:
    shutil.copyfile(FIXTURES / filename, tmp_path / filename)

    sync_family_crawler_rules([], root=tmp_path)

    rendered = (tmp_path / filename).read_text(encoding="utf-8")
    assert following_marker in rendered
    assert rendered.count(contract_rule) == 1
    assert rendered.count(CONTRACT_BEGIN) == 1
    assert rendered.count(CONTRACT_END) == 1


@pytest.mark.parametrize(
    ("filename", "following_block", "following_marker"),
    [
        (
            "robots.txt",
            "# Neighbor crawler policy\nDisallow: /vizinha/\n",
            "# Neighbor crawler policy",
        ),
        (
            "_headers",
            "# Neighbor crawler policy\n/vizinha/*\n  X-Robots-Tag: noindex\n",
            "# Neighbor crawler policy",
        ),
    ],
)
def test_legacy_empty_block_does_not_consume_an_adjacent_comment(
    tmp_path: Path,
    filename: str,
    following_block: str,
    following_marker: str,
) -> None:
    (tmp_path / filename).write_text(
        f"{CONTRACT_BEGIN}\n{following_block}", encoding="utf-8"
    )

    sync_family_crawler_rules([], root=tmp_path)

    rendered = (tmp_path / filename).read_text(encoding="utf-8")
    assert following_marker in rendered


@pytest.mark.parametrize(
    ("filename", "family_rule", "following_block"),
    [
        (
            "robots.txt",
            "Disallow: /analises-contratos-publicos/",
            (
                "# Neighbor crawler policy\n"
                "Disallow: /analises-contratos-publicos/\n"
                "Disallow: /vizinha/\n"
            ),
        ),
        (
            "_headers",
            "/analises-contratos-publicos/*",
            (
                "# Neighbor crawler policy\n"
                "/analises-contratos-publicos/*\n"
                "  X-Robots-Tag: noindex, nofollow, noarchive\n\n"
                "/vizinha/*\n"
                "  X-Robots-Tag: noindex\n"
            ),
        ),
    ],
)
def test_legacy_migration_removes_stale_duplicate_without_losing_marker(
    tmp_path: Path,
    filename: str,
    family_rule: str,
    following_block: str,
) -> None:
    (tmp_path / filename).write_text(
        f"{CONTRACT_BEGIN}\n{family_rule}\n{following_block}", encoding="utf-8"
    )

    sync_family_crawler_rules([], root=tmp_path)

    rendered = (tmp_path / filename).read_text(encoding="utf-8")
    assert "# Neighbor crawler policy" in rendered
    assert rendered.count(family_rule) == 1


@pytest.mark.parametrize(
    ("filename", "family_rule", "rule_body"),
    [
        (
            "robots.txt",
            "Disallow: /analises-contratos-publicos/",
            "Disallow: /analises-contratos-publicos/\n",
        ),
        (
            "_headers",
            "/analises-contratos-publicos/*",
            (
                "/analises-contratos-publicos/*\n"
                "  X-Robots-Tag: noindex, nofollow, noarchive\n\n"
            ),
        ),
    ],
)
def test_legacy_block_does_not_pair_with_a_later_duplicate_end_marker(
    tmp_path: Path,
    filename: str,
    family_rule: str,
    rule_body: str,
) -> None:
    (tmp_path / filename).write_text(
        (
            f"{CONTRACT_BEGIN}\n{rule_body}"
            "# Neighbor crawler policy\n"
            f"{CONTRACT_BEGIN}\n{rule_body}{CONTRACT_END}\n"
        ),
        encoding="utf-8",
    )

    sync_family_crawler_rules([], root=tmp_path)

    rendered = (tmp_path / filename).read_text(encoding="utf-8")
    assert "# Neighbor crawler policy" in rendered
    assert rendered.count(family_rule) == 1
    assert rendered.count(CONTRACT_BEGIN) == 1
    assert rendered.count(CONTRACT_END) == 1


@pytest.mark.parametrize(
    ("filename", "contract_rule_body", "market_rule_body"),
    [
        (
            "robots.txt",
            "Disallow: /analises-contratos-publicos/\n",
            "Disallow: /panorama-mercado-obras-publicas/\n",
        ),
        (
            "_headers",
            (
                "/analises-contratos-publicos/*\n"
                "  X-Robots-Tag: noindex, nofollow, noarchive\n\n"
            ),
            (
                "/panorama-mercado-obras-publicas/*\n"
                "  X-Robots-Tag: noindex, nofollow, noarchive\n\n"
            ),
        ),
    ],
)
def test_orphan_contract_end_after_neighbor_does_not_consume_neighbor(
    tmp_path: Path,
    filename: str,
    contract_rule_body: str,
    market_rule_body: str,
) -> None:
    market_block = f"{MARKET_BEGIN}\n{market_rule_body}{MARKET_END}\n"
    (tmp_path / filename).write_text(
        (
            f"{CONTRACT_BEGIN}\n{contract_rule_body}"
            f"{market_block}"
            f"{CONTRACT_END}\n"
        ),
        encoding="utf-8",
    )

    sync_family_crawler_rules([], root=tmp_path)

    rendered = (tmp_path / filename).read_text(encoding="utf-8")
    expected = f"{CONTRACT_BEGIN}\n{contract_rule_body}{CONTRACT_END}\n{market_block}"
    assert rendered == expected


@pytest.mark.parametrize(
    ("filename", "contract_rule_body", "market_rule_body"),
    [
        (
            "robots.txt",
            "Disallow: /analises-contratos-publicos/\n",
            "Disallow: /panorama-mercado-obras-publicas/\n",
        ),
        (
            "_headers",
            (
                "/analises-contratos-publicos/*\n"
                "  X-Robots-Tag: noindex, nofollow, noarchive\n\n"
            ),
            (
                "/panorama-mercado-obras-publicas/*\n"
                "  X-Robots-Tag: noindex, nofollow, noarchive\n\n"
            ),
        ),
    ],
)
def test_market_family_before_contract_remains_byte_identical(
    tmp_path: Path,
    filename: str,
    contract_rule_body: str,
    market_rule_body: str,
) -> None:
    market_block = f"{MARKET_BEGIN}\n{market_rule_body}{MARKET_END}\n"
    contract_block = f"{CONTRACT_BEGIN}\n{contract_rule_body}{CONTRACT_END}\n"
    path = tmp_path / filename
    path.write_text(f"{market_block}{contract_block}", encoding="utf-8")

    sync_family_crawler_rules([], root=tmp_path)
    once = path.read_bytes()
    sync_family_crawler_rules([], root=tmp_path)

    assert once == f"{market_block}{contract_block}".encode()
    assert path.read_bytes() == once


def test_robot_rule_for_another_user_agent_is_not_an_orphan_duplicate(
    tmp_path: Path,
) -> None:
    archive_allow = "Allow: /analises-contratos-publicos/publica/\n"
    contract_block = (
        f"{CONTRACT_BEGIN}\n"
        "Disallow: /analises-contratos-publicos/\n"
        f"{CONTRACT_END}\n"
    )
    original = (
        "User-agent: ArchiveBot\n"
        "Disallow: /\n"
        f"{archive_allow}"
        "User-agent: *\n"
        f"{contract_block}"
    )
    path = tmp_path / "robots.txt"
    path.write_text(original, encoding="utf-8")

    sync_family_crawler_rules([], root=tmp_path)

    assert path.read_text(encoding="utf-8") == original


def test_non_crawler_headers_for_family_subpath_remain_outside_owned_block(
    tmp_path: Path,
) -> None:
    security_block = (
        "# Neighbor security policy\n"
        "/analises-contratos-publicos/documentos/*\n"
        "  Cache-Control: no-store\n"
        "  Content-Security-Policy: default-src 'none'\n\n"
    )
    contract_block = (
        f"{CONTRACT_BEGIN}\n"
        "/analises-contratos-publicos/*\n"
        "  X-Robots-Tag: noindex, nofollow, noarchive\n\n"
        f"{CONTRACT_END}\n"
    )
    original = f"{security_block}{contract_block}"
    path = tmp_path / "_headers"
    path.write_text(original, encoding="utf-8")

    sync_family_crawler_rules([], root=tmp_path)

    assert path.read_text(encoding="utf-8") == original


def test_legacy_header_migration_preserves_non_crawler_directives(
    tmp_path: Path,
) -> None:
    legacy = (
        f"{CONTRACT_BEGIN}\n"
        "/analises-contratos-publicos/*\n"
        "  X-Robots-Tag: noindex, nofollow, noarchive\n"
        "  Cache-Control: no-store\n"
        "  Content-Security-Policy: default-src 'none'\n\n"
        "# Neighbor crawler policy\n"
        "/vizinha/*\n"
        "  X-Robots-Tag: noindex\n"
    )
    expected = (
        f"{CONTRACT_BEGIN}\n"
        "/analises-contratos-publicos/*\n"
        "  X-Robots-Tag: noindex, nofollow, noarchive\n"
        "  Cache-Control: no-store\n"
        "  Content-Security-Policy: default-src 'none'\n\n"
        f"{CONTRACT_END}\n"
        "# Neighbor crawler policy\n"
        "/vizinha/*\n"
        "  X-Robots-Tag: noindex\n"
    )
    path = tmp_path / "_headers"
    path.write_text(legacy, encoding="utf-8")

    sync_family_crawler_rules([], root=tmp_path)
    once = path.read_bytes()
    sync_family_crawler_rules([], root=tmp_path)

    assert once == expected.encode()
    assert path.read_bytes() == once
    assert path.read_text(encoding="utf-8").count("/analises-contratos-publicos/*") == 1


def test_legacy_header_migration_preserves_index_override_non_crawler_directives(
    tmp_path: Path,
) -> None:
    slug = "preserved-slug"
    selector = f"/analises-contratos-publicos/{slug}/*"
    legacy = (
        f"{CONTRACT_BEGIN}\n"
        "/analises-contratos-publicos/*\n"
        "  X-Robots-Tag: noindex, nofollow, noarchive\n\n"
        f"{selector}\n"
        "  X-Robots-Tag: index, follow\n"
        "  Cache-Control: no-store\n"
        "  Content-Security-Policy: default-src 'none'\n\n"
        "# Neighbor crawler policy\n"
        "/vizinha/*\n"
        "  X-Robots-Tag: noindex\n"
    )
    expected = (
        f"{CONTRACT_BEGIN}\n"
        "/analises-contratos-publicos/*\n"
        "  X-Robots-Tag: noindex, nofollow, noarchive\n\n"
        f"{selector}\n"
        "  X-Robots-Tag: index, follow\n"
        "  Cache-Control: no-store\n"
        "  Content-Security-Policy: default-src 'none'\n\n"
        f"{CONTRACT_END}\n"
        "# Neighbor crawler policy\n"
        "/vizinha/*\n"
        "  X-Robots-Tag: noindex\n"
    )
    path = tmp_path / "_headers"
    path.write_text(legacy, encoding="utf-8")
    decision = SimpleNamespace(
        state="PUBLISHABLE_INDEX", indexable=True, slug=slug
    )

    sync_family_crawler_rules([({}, decision)], root=tmp_path)
    once = path.read_bytes()
    sync_family_crawler_rules([({}, decision)], root=tmp_path)

    assert once == expected.encode()
    assert path.read_bytes() == once
    rendered = path.read_text(encoding="utf-8")
    assert rendered.count("/analises-contratos-publicos/*") == 1
    assert rendered.count(selector) == 1


def test_stale_index_override_retains_non_crawler_directives_without_xrobots(
    tmp_path: Path,
) -> None:
    selector = "/analises-contratos-publicos/former-slug/*"
    original = (
        f"{CONTRACT_BEGIN}\n"
        "/analises-contratos-publicos/*\n"
        "  X-Robots-Tag: noindex, nofollow, noarchive\n\n"
        f"{selector}\n"
        "  X-Robots-Tag: index, follow\n"
        "  Cache-Control: no-store\n"
        "  Content-Security-Policy: default-src 'none'\n\n"
        f"{CONTRACT_END}\n"
    )
    expected = (
        f"{CONTRACT_BEGIN}\n"
        "/analises-contratos-publicos/*\n"
        "  X-Robots-Tag: noindex, nofollow, noarchive\n\n"
        f"{selector}\n"
        "  Cache-Control: no-store\n"
        "  Content-Security-Policy: default-src 'none'\n\n"
        f"{CONTRACT_END}\n"
    )
    path = tmp_path / "_headers"
    path.write_text(original, encoding="utf-8")

    sync_family_crawler_rules([], root=tmp_path)
    once = path.read_bytes()
    sync_family_crawler_rules([], root=tmp_path)

    rendered = path.read_text(encoding="utf-8")
    assert once == expected.encode()
    assert path.read_bytes() == once
    assert rendered.count(selector) == 1
    assert f"{selector}\n  X-Robots-Tag:" not in rendered


@pytest.mark.parametrize(
    ("filename", "prefix", "stale_override", "expected"),
    [
        (
            "robots.txt",
            "User-agent: *\n",
            "Allow: /analises-contratos-publicos/former-slug/\n",
            "User-agent: *\n",
        ),
        (
            "_headers",
            "",
            (
                "/analises-contratos-publicos/former-slug/*\n"
                "  X-Robots-Tag: index, follow\n\n"
            ),
            "",
        ),
    ],
)
def test_stale_index_override_is_removed_from_owned_scope(
    tmp_path: Path,
    filename: str,
    prefix: str,
    stale_override: str,
    expected: str,
) -> None:
    contract_rule_body = (
        "Disallow: /analises-contratos-publicos/\n"
        if filename == "robots.txt"
        else (
            "/analises-contratos-publicos/*\n"
            "  X-Robots-Tag: noindex, nofollow, noarchive\n\n"
        )
    )
    contract_block = f"{CONTRACT_BEGIN}\n{contract_rule_body}{CONTRACT_END}\n"
    path = tmp_path / filename
    path.write_text(f"{prefix}{contract_block}{stale_override}", encoding="utf-8")

    sync_family_crawler_rules([], root=tmp_path)

    assert path.read_text(encoding="utf-8") == f"{expected}{contract_block}"


@pytest.mark.parametrize(
    ("filename", "prefix", "contract_rule_body", "duplicate_at_eof"),
    [
        (
            "robots.txt",
            "User-agent: *\n",
            "Disallow: /analises-contratos-publicos/\n",
            "Disallow: /analises-contratos-publicos/",
        ),
        (
            "_headers",
            "",
            (
                "/analises-contratos-publicos/*\n"
                "  X-Robots-Tag: noindex, nofollow, noarchive\n\n"
            ),
            (
                "/analises-contratos-publicos/*\n"
                "  X-Robots-Tag: noindex, nofollow, noarchive"
            ),
        ),
    ],
)
def test_canonical_duplicate_at_eof_is_removed_on_first_run(
    tmp_path: Path,
    filename: str,
    prefix: str,
    contract_rule_body: str,
    duplicate_at_eof: str,
) -> None:
    contract_block = f"{CONTRACT_BEGIN}\n{contract_rule_body}{CONTRACT_END}\n"
    expected = f"{prefix}{contract_block}".encode()
    path = tmp_path / filename
    path.write_text(
        f"{prefix}{contract_block}{duplicate_at_eof}", encoding="utf-8"
    )

    sync_family_crawler_rules([], root=tmp_path)
    once = path.read_bytes()
    sync_family_crawler_rules([], root=tmp_path)

    assert once == expected
    assert path.read_bytes() == once


def test_missing_robot_marker_inserts_block_in_wildcard_group(
    tmp_path: Path,
) -> None:
    contract_block = (
        f"{CONTRACT_BEGIN}\n"
        "Disallow: /analises-contratos-publicos/\n"
        f"{CONTRACT_END}\n"
    )
    original = (
        "User-agent: *\n"
        "Disallow: /private/\n"
        "User-agent: ArchiveBot\n"
        "Disallow: /\n"
    )
    expected = (
        "User-agent: *\n"
        "Disallow: /private/\n\n"
        f"{contract_block}"
        "User-agent: ArchiveBot\n"
        "Disallow: /\n"
    ).encode()
    path = tmp_path / "robots.txt"
    path.write_text(original, encoding="utf-8")

    sync_family_crawler_rules([], root=tmp_path)
    once = path.read_bytes()
    sync_family_crawler_rules([], root=tmp_path)

    assert once == expected
    assert path.read_bytes() == once


def test_missing_marker_preserves_combined_wildcard_user_agent_group(
    tmp_path: Path,
) -> None:
    contract_block = (
        f"{CONTRACT_BEGIN}\n"
        "Disallow: /analises-contratos-publicos/\n"
        f"{CONTRACT_END}\n"
    )
    original = (
        "User-agent: *\n"
        "User-agent: Googlebot\n"
        "Disallow: /private/\n"
        "User-agent: ArchiveBot\n"
        "Disallow: /\n"
    )
    expected = (
        "User-agent: *\n"
        "User-agent: Googlebot\n"
        "Disallow: /private/\n\n"
        f"{contract_block}"
        "User-agent: ArchiveBot\n"
        "Disallow: /\n"
    ).encode()
    path = tmp_path / "robots.txt"
    path.write_text(original, encoding="utf-8")

    sync_family_crawler_rules([], root=tmp_path)
    once = path.read_bytes()
    sync_family_crawler_rules([], root=tmp_path)

    assert once == expected
    assert path.read_bytes() == once


def _robots_directives(payload: bytes) -> list[bytes]:
    return [
        line
        for line in payload.splitlines(keepends=True)
        if line.startswith((b"Allow:", b"Disallow:"))
    ]


def test_cli_build_twice_is_idempotent_and_preserves_crawler_policy() -> None:
    isolated_root = Path(os.environ["CONFENGE_CONTRACT_ANALYSIS_ROOT"])
    for filename in ("robots.txt", "_headers"):
        shutil.copyfile(FIXTURES / filename, isolated_root / filename)
    original_robots_policy = _robots_directives(
        (isolated_root / "robots.txt").read_bytes()
    )

    first = subprocess.run(
        [sys.executable, "-m", "scripts.contract_analysis", "build"],
        cwd=ROOT,
        capture_output=True,
        text=True,
        check=False,
    )
    assert first.returncode == 0, first.stderr + first.stdout
    once = {
        filename: (isolated_root / filename).read_bytes()
        for filename in ("robots.txt", "_headers")
    }
    assert _robots_directives(once["robots.txt"]) == original_robots_policy

    second = subprocess.run(
        [sys.executable, "-m", "scripts.contract_analysis", "build"],
        cwd=ROOT,
        capture_output=True,
        text=True,
        check=False,
    )
    assert second.returncode == 0, second.stderr + second.stdout
    twice = {
        filename: (isolated_root / filename).read_bytes()
        for filename in ("robots.txt", "_headers")
    }
    assert twice == once
