#!/usr/bin/env python3
"""Run the exact gated bundle's controller over pinned SSH, without host installation."""
from __future__ import annotations

import argparse
import hashlib
import importlib.util
import json
import re
import shlex
import subprocess
import tarfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
CONTROL = ROOT / "deploy/netcup/lib/release_control.py"
MEMBER = "ops/lib/release_control.py"


def validate_checkout(sha: str) -> None:
    head = subprocess.check_output(["git", "rev-parse", "HEAD"], cwd=ROOT, text=True).strip()
    if head != sha:
        raise ValueError("checkout differs from exact release SHA")
    # Reports outside the controller closure may have been generated by the
    # failed acceptance that now needs rollback. No control source may drift,
    # including staged changes or an untracked import shadowing a real module.
    dirty = subprocess.check_output(
        ["git", "status", "--porcelain", "--untracked-files=all", "--", "deploy/netcup"],
        cwd=ROOT, text=True,
    )
    if dirty:
        raise ValueError("release controller checkout is not clean")


def verified_controller(directory: Path, sha: str) -> tuple[bytes, str, str]:
    spec = importlib.util.spec_from_file_location("bundle_release_control", CONTROL)
    control = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(control)
    control.validate_sha(sha)
    bundle, manifest = control.validate_incoming(directory.parent, sha, directory)
    with tarfile.open(bundle, "r:gz") as archive:
        names = [member.name for member in archive.getmembers()]
        if len(names) != len(set(names)):
            raise ValueError("duplicate bundle member")
        selected = [archive.getmember(name) for name in (MEMBER, "metadata/files.sha256")]
        if any(not member.isfile() for member in selected):
            raise ValueError("controller and payload manifest must be regular files")
        code, payload = [archive.extractfile(member).read() for member in selected]
    digest = hashlib.sha256(code).hexdigest()
    entries = [line for line in payload.decode("utf-8").splitlines() if line.endswith("  " + MEMBER)]
    if entries != [f"{digest}  {MEMBER}"]:
        raise ValueError("controller differs from payload manifest")
    if code != CONTROL.read_bytes():
        raise ValueError("bundle controller differs from exact gated checkout")
    print(f"NETCUP_CONTROL_VERIFIED sha={sha} bundle={manifest['artifact']['sha256']} controller={digest}", flush=True)
    return code, digest, manifest["artifact"]["sha256"]


def remote_command(operation: str, sha: str, digest: str, upload_dir: str | None = None,
                   expected_current: str | None = None, *, artifact_sha256: str,
                   controller_sha: str | None = None) -> str:
    if operation not in {"stage", "verify", "promote", "rollback", "inventory"}:
        raise ValueError("unsupported controller operation")
    if not re.fullmatch(r"[0-9a-f]{40}", sha) or not re.fullmatch(r"[0-9a-f]{64}", digest):
        raise ValueError("invalid controller identity")
    controller_sha = controller_sha or sha
    if not re.fullmatch(r"[0-9a-f]{40}", controller_sha) or not re.fullmatch(r"[0-9a-f]{64}", artifact_sha256):
        raise ValueError("invalid verified bundle identity")
    if upload_dir is not None and (operation != "stage" or not re.fullmatch(
        rf"/opt/confenge-web/incoming/\.upload-{sha}-[0-9]+-[0-9]+", upload_dir
    )):
        raise ValueError("unexpected upload directory")
    bootstrap = (
        "import hashlib,hmac,os,sys;code=sys.stdin.buffer.read();"
        f"expected={digest!r};"
        "actual=hashlib.sha256(code).hexdigest();"
        "hmac.compare_digest(actual,expected) or sys.exit('controller transport digest mismatch');"
        "os.environ['CONFENGE_RELEASE_CONTROL_SHA256']=actual;"
        f"os.environ['CONFENGE_EXPECTED_RELEASE_SHA']={controller_sha!r};"
        f"os.environ['CONFENGE_EXPECTED_RELEASE_ARTIFACT_SHA256']={artifact_sha256!r};"
        "exec(compile(code,'<verified-release-bundle-controller>','exec'))"
    )
    argv = ["env", "PYTHONDONTWRITEBYTECODE=1", "CONFENGE_LOCAL_ORIGIN=http://127.0.0.1:8088",
            "python3", "-c", bootstrap, operation, sha]
    if upload_dir:
        argv += ["--upload-dir", upload_dir]
    if operation == "promote":
        if expected_current != "NONE" and not re.fullmatch(r"[0-9a-f]{40}", expected_current or ""):
            raise ValueError("promotion requires the predecessor observed before stage")
        argv += ["--expected-current", expected_current]
    elif operation == "rollback" and expected_current is not None:
        if not re.fullmatch(r"[0-9a-f]{40}", expected_current):
            raise ValueError("compensating rollback requires the exact failed release SHA")
        argv += ["--expected-current", expected_current]
    return shlex.join(argv)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--bundle-directory", type=Path, required=True)
    parser.add_argument("--sha", required=True)
    parser.add_argument("--operation", choices=("stage", "verify", "promote", "rollback", "inventory"), required=True)
    parser.add_argument("--target", required=True)
    parser.add_argument("--ssh-option", action="append", default=[])
    parser.add_argument("--upload-dir")
    parser.add_argument("--expected-current")
    parser.add_argument("--rollback-target", help="Existing target SHA; controller remains pinned to --sha")
    parser.add_argument("--output", type=Path, help="Capture the verified inventory as a private evidence file")
    args = parser.parse_args()
    if not re.fullmatch(r"[a-z_][a-z0-9_-]*@[A-Za-z0-9.:-]+", args.target):
        parser.error("invalid pinned SSH target")
    validate_checkout(args.sha)
    code, digest, artifact_digest = verified_controller(args.bundle_directory, args.sha)
    if args.rollback_target and args.operation != "rollback":
        parser.error("rollback target only applies to rollback")
    command = remote_command(args.operation, args.rollback_target or args.sha, digest,
                             args.upload_dir, args.expected_current,
                             artifact_sha256=artifact_digest, controller_sha=args.sha)
    if args.output and args.operation != "inventory":
        parser.error("output capture only applies to read-only inventory")
    result = subprocess.run(["ssh", *args.ssh_option, args.target, command], input=code,
                            check=True, stdout=subprocess.PIPE if args.output else None)
    if args.output:
        payload = json.loads(result.stdout)
        if payload.get("release_sha") != args.sha:
            parser.error("inventory differs from exact served release SHA")
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
