/**
 * WS-G (BOFU-FECHAMENTO-20260919, L1-a): the CTA/form census classifies every
 * non-capture <form> on a visitor page as `tool_form` and each one must degrade
 * explicitly without JavaScript: a <noscript> message outside any capture form,
 * or the tools pattern (a rendered status + controls disabled until the
 * runtime enables them). Before this test the census left the tool forms out,
 * so nobody checked what a visitor without JavaScript sees.
 *
 * Counter-proof: a synthetic page whose tool form has neither is `none` and
 * fails; the shipped tree has exactly one such form, registered below as a
 * dated pendency (the page is generated by scripts/organic/breakout.py and
 * its rebuild rewrites unrelated bytes, so the note enters with that generator).
 */
import assert from "node:assert/strict";
import fs from "node:fs";
import { buildInventory, toolForms } from "../../scripts/commercial/cta_form_next_state_audit.mjs";

// --- Unit: classification and degradation evidence ------------------------
const lead = '<form method="post" action="/.netlify/functions/lead"><noscript><p class="form-hint form-nojs-note">Sem JavaScript, este formulário não envia. Use o <a href="mailto:x@example.test">e-mail</a>.</p></noscript><input name="nome"></form>';
const bareTool = '<form id="f" class="tool-form" method="post" action="/x/"><select name="a"></select><button type="button">Calcular</button></form>';
const runtimeTool = '<p data-tool-runtime-status role="status">Ative o JavaScript para calcular no navegador.</p><form id="f" class="tool-form" method="post" action="/x/"><fieldset data-tool-runtime-fields disabled><select name="a"></select><button class="tool-run" type="submit" disabled>Calcular</button></fieldset></form>';
const noscriptTool = '<noscript><p>Sem JavaScript o formulário permanece bloqueado.</p></noscript><form id="d" method="post" action="#"><button type="submit">Ver</button></form>';

assert.deepEqual(toolForms(`<main>${lead}</main>`, "/x/"), [], "a lead capture form is not a tool form");
const bare = toolForms(`<main>${lead}${bareTool}</main>`, "/x/");
assert.equal(bare.length, 1);
assert.equal(bare[0].kind, "tool_form");
assert.equal(bare[0].nojs_degradation, "none", "the capture form's own noscript note must not vouch for the tool");
assert.equal(toolForms(`<main>${runtimeTool}</main>`, "/x/")[0].nojs_degradation, "runtime_status");
assert.equal(toolForms(`<main>${noscriptTool}</main>`, "/x/")[0].nojs_degradation, "noscript_note");
// Status without disabled controls is a promise, not a degradation.
assert.equal(toolForms('<main><p data-tool-runtime-status role="status">Ative o JavaScript.</p><form id="f" method="post" action="/x/"><button type="submit">Ir</button></form></main>', "/x/")[0].nojs_degradation, "none");

// --- Shipped tree ------------------------------------------------------------
const report = buildInventory();
const tools = report.tool_forms;
assert.ok(Array.isArray(tools) && tools.length >= 7, `tool forms census: ${tools.length}`);
assert.ok(tools.every((form) => form.kind === "tool_form"));
assert.equal(tools.filter((form) => form.route.startsWith("/piloto/") || form.route.startsWith("/nurture/")).length, 0, "visitor pages only");
// Tool forms never inflate the recorded CTA contract.
assert.equal(report.coverage.declared_ctas, report.contract.expected_declared_ctas);
assert.ok(!report.surfaces.some((surface) => surface.forms.some((form) => form.kind === "tool_form")));

// The seven tool forms the census used to leave out (critic, 2026-09-19) plus
// the CNPJ lookup form of /analise-cnpj/ (its lead form is a capture surface).
const expectedRoutes = new Set([
  "/analise-cnpj/",
  "/conflitos/",
  "/conteudos/sinapi-desonerado-nao-desonerado/",
  "/ferramentas/checklist-reequilibrio/",
  "/ferramentas/diagnostico-defesa-margem/",
  "/ferramentas/limite-acrescimos-supressoes/",
  "/ferramentas/matriz-atraso-obra/",
  "/ferramentas/prontidao-tecnica-obra-privada/",
]);
assert.deepEqual(new Set(tools.map((form) => form.route)), expectedRoutes, JSON.stringify(tools.map((f) => f.route)));

// Pendência datada, route-exact (2026-09-19, #705): o alinhador SINAPI
// (form.breakout-tool, gerado por scripts/organic/breakout.py) não explica o
// caso sem JavaScript; o botão é type="button" e nada acontece. A nota entra
// pelo gerador; ao entrar, este carve-out reprova sozinho e sai daqui.
const PENDING_NO_DEGRADATION = new Map([
  ["/conteudos/sinapi-desonerado-nao-desonerado/#breakout-tool", "2026-09-19 #705 breakout.py sem nota noscript"],
]);
for (const form of tools) {
  const key = `${form.route}#${form.form_id || form.form_class}`;
  if (PENDING_NO_DEGRADATION.has(key)) {
    assert.equal(form.nojs_degradation, "none", `${key}: degradação publicada; retire a pendência`);
    continue;
  }
  assert.notEqual(form.nojs_degradation, "none", `${key}: sem JavaScript o formulário de ferramenta precisa de mensagem visível ou degradação explícita`);
}
assert.equal(
  tools.filter((form) => form.nojs_degradation === "none").length,
  PENDING_NO_DEGRADATION.size,
  "every tool form without degradation is a named, dated pendency",
);

// The recorded inventory carries the same census.
const recorded = JSON.parse(fs.readFileSync("docs/commercial/cta-form-next-state-inventory.json", "utf8"));
assert.deepEqual(recorded.tool_forms, tools, "recorded tool_forms must match the derived census");

console.log(`tool-forms-nojs: tool_forms=${tools.length} pending=${PENDING_NO_DEGRADATION.size}`);
