/**
 * CORE 01–10 are always in the matrix. Expansions 11–14 run when included.
 * Omitting a CORE id from a candidate manifest is a finding, not a hidden pass.
 */
export const CORE_IDS = ["01", "02", "03", "04", "05", "06", "07", "08", "09", "10"];
export const EXPANSION_IDS = ["11", "12", "13", "14"];

export const CORE_CAMPAIGNS = [
  {
    id: "01",
    title: "mapa de demanda SEO",
    owner: "01",
    expected_producer_artifacts: [
      "docs/campaigns/inb-20260911/01/handoff.json",
      "data/organic/purchase-route-map.v1.json",
    ],
    baseline_sources: [
      "data/organic/bofu-intent-matrix.json",
      "data/corporate/intent-family-matrix.v1.json",
    ],
    public_routes: [],
  },
  {
    id: "02",
    title: "captura e atribuição",
    owner: "02",
    expected_producer_artifacts: ["docs/campaigns/inb-20260911/02/handoff.json"],
    baseline_sources: [
      "netlify/functions/lead.cjs",
      "netlify/functions/lib/inbound-handoff.cjs",
      "netlify/functions/lib/event-contract.cjs",
    ],
    public_routes: ["/triagem-tecnica/"],
  },
  {
    id: "03",
    title: "quantitativos e orçamento",
    owner: "03",
    expected_producer_artifacts: ["docs/campaigns/inb-20260911/03/handoff.json"],
    baseline_sources: ["quantitativos-orcamento-obras/index.html"],
    public_routes: ["/quantitativos-orcamento-obras/"],
  },
  {
    id: "04",
    title: "compatibilização",
    owner: "04",
    expected_producer_artifacts: ["docs/campaigns/inb-20260911/04/handoff.json"],
    baseline_sources: ["servicos/index.html"],
    public_routes: ["/servicos/"],
    dedicated_route_proposed: true,
  },
  {
    id: "05",
    title: "revisão de projetos",
    owner: "05",
    expected_producer_artifacts: ["docs/campaigns/inb-20260911/05/handoff.json"],
    baseline_sources: ["servicos/index.html"],
    public_routes: ["/servicos/"],
    dedicated_route_proposed: true,
  },
  {
    id: "06",
    title: "prova técnica privada",
    owner: "06",
    expected_producer_artifacts: ["docs/campaigns/inb-20260911/06/handoff.json"],
    baseline_sources: ["casos/medicao-glosa-demonstrativo/index.html", "entregas/index.html"],
    public_routes: ["/casos/medicao-glosa-demonstrativo/", "/entregas/"],
  },
  {
    id: "07",
    title: "prontidão privada",
    owner: "07",
    expected_producer_artifacts: ["docs/campaigns/inb-20260911/07/handoff.json"],
    baseline_sources: [
      "ferramentas/prontidao-tecnica-obra-privada/index.html",
      "assets/js/private-project-technical-readiness.cjs",
    ],
    public_routes: ["/ferramentas/prontidao-tecnica-obra-privada/"],
  },
  {
    id: "08",
    title: "tração pública",
    owner: "08",
    expected_producer_artifacts: ["docs/campaigns/inb-20260911/08/handoff.json"],
    baseline_sources: [
      "medicoes-glosas-obras-publicas/index.html",
      "aditivos-obras-publicas/index.html",
      "servicos-obras-publicas/index.html",
    ],
    public_routes: [
      "/medicoes-glosas-obras-publicas/",
      "/aditivos-obras-publicas/",
      "/servicos-obras-publicas/",
    ],
  },
  {
    id: "09",
    title: "hubs de navegação",
    owner: "09",
    expected_producer_artifacts: ["docs/campaigns/inb-20260911/09/handoff.json"],
    baseline_sources: [
      "servicos/index.html",
      "conteudos/index.html",
      "casos/index.html",
      "entregas/index.html",
    ],
    public_routes: ["/servicos/", "/conteudos/", "/casos/", "/entregas/"],
  },
  {
    id: "10",
    title: "observatório GSC",
    owner: "10",
    expected_producer_artifacts: ["docs/campaigns/inb-20260911/10/handoff.json"],
    baseline_sources: ["scripts/site/test_search_observation.mjs"],
    public_routes: [],
  },
];

export const EXPANSION_CAMPAIGNS = [
  {
    id: "11",
    title: "parcerias e referências",
    owner: "11",
    expected_producer_artifacts: ["docs/campaigns/inb-20260911/11/handoff.json"],
    leak_href_needles: ["/parcerias/", "/referencias-clientes/"],
  },
  {
    id: "12",
    title: "projetos complementares",
    owner: "12",
    expected_producer_artifacts: ["docs/campaigns/inb-20260911/12/handoff.json"],
    leak_href_needles: ["/projetos-complementares/", "/complementares/"],
  },
  {
    id: "13",
    title: "expansão 13",
    owner: "13",
    expected_producer_artifacts: ["docs/campaigns/inb-20260911/13/handoff.json"],
    leak_href_needles: [],
  },
  {
    id: "14",
    title: "expansão 14",
    owner: "14",
    expected_producer_artifacts: ["docs/campaigns/inb-20260911/14/handoff.json"],
    leak_href_needles: [],
  },
];

export const PURCHASE_PATHS = [
  {
    id: "orcamento-privado-sem-licitacao",
    label: "orçamento privado sem licitação",
    core: "03",
    intent_family: "orcar_planejar_decidir",
    offer_id: "quantity_takeoff_budgeting",
    routes: ["/quantitativos-orcamento-obras/"],
    files: ["quantitativos-orcamento-obras/index.html"],
    contact_mode: "capture_form_or_whatsapp",
    requested_indexability: "index",
    must_mention: ["orçamento", "quantitativo"],
    private_not_licitacao: true,
    proof_file: null,
  },
  {
    id: "arquiteto-complementares",
    label: "arquiteto buscando complementares",
    core: "12",
    expansion: true,
    intent_family: "projetar_revisar_compatibilizar",
    offer_id: "complementary_engineering_project_review",
    routes: ["/projetos-complementares-engenharia/", "/servicos/", "/triagem-tecnica/"],
    files: [
      "projetos-complementares-engenharia/index.html",
      "servicos/index.html",
      "triagem-tecnica/index.html",
    ],
    contact_mode: "capture_form_or_whatsapp",
    requested_indexability: "index",
    dedicated_files: ["projetos-complementares-engenharia/index.html"],
    dedicated_missing_ok: false,
    must_mention: ["projeto", "estrutural|hidrossanit|elétric|completar"],
  },
  {
    id: "revisao-vs-compatibilizacao",
    label: "comprador diferenciando revisão e compatibilização",
    core: "04",
    also: "05",
    intent_family: "projetar_revisar_compatibilizar",
    offer_id: "bim_coordination_clash_register",
    routes: ["/servicos/"],
    files: ["servicos/index.html"],
    contact_mode: "capture_form_or_whatsapp",
    requested_indexability: "index",
    must_mention: ["revis", "compatibiliz"],
    distinguish_purchase: true,
  },
  {
    id: "amostra-depois-necessidade",
    label: "visitante que consulta amostra e depois descreve a necessidade",
    core: "06",
    intent_family: "orcar_planejar_decidir",
    offer_id: "quantity_takeoff_budgeting",
    routes: ["/casos/medicao-glosa-demonstrativo/", "/triagem-tecnica/"],
    files: ["casos/medicao-glosa-demonstrativo/index.html", "triagem-tecnica/index.html"],
    contact_mode: "capture_form_or_whatsapp",
    requested_indexability: "index",
    sample_then_contact: true,
    proof_file: "casos/medicao-glosa-demonstrativo/index.html",
  },
  {
    id: "ferramenta-completa-sem-contato",
    label: "ferramenta completa sem contato",
    core: "07",
    intent_family: "orcar_planejar_decidir",
    offer_id: "private_project_technical_readiness_assessment",
    routes: ["/ferramentas/prontidao-tecnica-obra-privada/"],
    files: ["ferramentas/prontidao-tecnica-obra-privada/index.html"],
    contact_mode: "none_for_result",
    requested_indexability: "noindex",
    no_contact_required: true,
  },
  {
    id: "construtora-medicao-glosa",
    label: "construtora com medição/glosa",
    core: "08",
    intent_family: "executar_proteger_contrato_publico",
    offer_id: null,
    routes: ["/medicoes-glosas-obras-publicas/", "/casos/medicao-glosa-demonstrativo/"],
    files: [
      "medicoes-glosas-obras-publicas/index.html",
      "casos/medicao-glosa-demonstrativo/index.html",
    ],
    contact_mode: "capture_form",
    requested_indexability: "index",
    must_mention: ["medi", "glosa"],
    preserve_b2g: true,
  },
  {
    id: "alteracao-aditivo",
    label: "alteração/aditivo",
    core: "08",
    intent_family: "executar_proteger_contrato_publico",
    offer_id: null,
    routes: ["/aditivos-obras-publicas/"],
    files: ["aditivos-obras-publicas/index.html"],
    contact_mode: "capture_form",
    requested_indexability: "index",
    must_mention: ["aditiv"],
    preserve_b2g: true,
  },
  {
    id: "inspecao-local-nao-confirmado",
    label: "inspeção com localização ainda não confirmada",
    core: "05",
    intent_family: "inspecionar_diagnosticar",
    offer_id: "building_inspection_pathology",
    routes: ["/servicos/", "/triagem-tecnica/"],
    files: ["servicos/index.html", "triagem-tecnica/index.html"],
    contact_mode: "capture_form_or_whatsapp",
    requested_indexability: "index",
    needs_context_location: true,
    must_mention: ["inspe", "diagn"],
  },
  {
    id: "assistencia-material-sigiloso",
    label: "assistência técnica com material sigiloso",
    core: "06",
    intent_family: "produzir_prova_tecnica",
    offer_id: "civil_building_technical_assistance",
    routes: ["/servicos/", "/triagem-tecnica/", "/conflitos/"],
    files: ["servicos/index.html", "triagem-tecnica/index.html", "conflitos/index.html"],
    contact_mode: "capture_form_or_whatsapp",
    requested_indexability: "index",
    secret_material: true,
    must_mention: ["assist", "conflito"],
  },
  {
    id: "sst-documento-indefinido",
    label: "SST com documento ainda indefinido",
    core: "09",
    intent_family: "organizar_sst",
    offer_id: "sst_risk_documentation_diagnosis",
    routes: ["/servicos/", "/triagem-tecnica/"],
    files: ["servicos/index.html", "triagem-tecnica/index.html"],
    contact_mode: "capture_form_or_whatsapp",
    requested_indexability: "index",
    undefined_document: true,
    must_mention: ["segurança do trabalho|\\bSST\\b"],
  },
];

export const OWNED_TREES = [
  "tests/campaigns/inb_20260911/15/",
  "docs/campaigns/inb-20260911/15/",
];
